### ISSUE TITLE
installtion of deproject

### ISSUE THREAD

**Issue by ksk321** [sherpa-deproject/deproject#19]
Dear sir,
   I am using CIAO4.14 IN Ubuntu20.04LTS system. I am trying to test using  "sudo python3 setup.py test". But I get following errors:

skk@skk-HP-15-Notebook-PC:~/deproject-main$ sudo python3 setup.py test
running pytest
running egg_info
writing src/deproject.egg-info/PKG-INFO
writing dependency_links to src/deproject.egg-info/dependency_links.txt
writing requirements to src/deproject.egg-info/requires.txt
writing top-level names to src/deproject.egg-info/top_level.txt
reading manifest file 'src/deproject.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/deproject.egg-info/SOURCES.txt'
running build_ext
======================================================= test session starts ========================================================
platform linux -- Python 3.8.10, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/skk/deproject-main/.hypothesis/examples')
rootdir: /home/skk/deproject-main
plugins: openfiles-0.4.0, doctestplus-0.5.0, remotedata-0.3.2, arraydiff-0.3, hypothesis-4.36.2, astropy-header-0.1.2
collected 0 items / 2 errors                                                                                                       

============================================================== ERRORS ==============================================================
_____________________________________________ ERROR collecting tests/test_deproject.py _____________________________________________
ImportError while importing test module '/home/skk/deproject-main/tests/test_deproject.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_deproject.py:13: in <module>
    from deproject.deproject import Deproject
/usr/local/lib/python3.8/dist-packages/deproject-0.2.1-py3.8.egg/deproject/__init__.py:12: in <module>
    ???
/usr/local/lib/python3.8/dist-packages/deproject-0.2.1-py3.8.egg/deproject/deproject.py:25: in <module>
    ???
/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/plot/__init__.py:59: in <module>
    from sherpa.utils import NoNewAttributesAfterInit, erf, SherpaFloat, \
/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/utils/__init__.py:43: in <module>
    from sherpa.utils import _utils, _psf
E   ImportError: cannot import name '_psf' from partially initialized module 'sherpa.utils' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/utils/__init__.py)
____________________________________________ ERROR collecting tests/test_simplegraph.py ____________________________________________
ImportError while importing test module '/home/skk/deproject-main/tests/test_simplegraph.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_simplegraph.py:10: in <module>
    from deproject.simplegraph import SimpleGraph
/usr/local/lib/python3.8/dist-packages/deproject-0.2.1-py3.8.egg/deproject/__init__.py:12: in <module>
    ???
/usr/local/lib/python3.8/dist-packages/deproject-0.2.1-py3.8.egg/deproject/deproject.py:25: in <module>
    ???
/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/plot/__init__.py:59: in <module>
    from sherpa.utils import NoNewAttributesAfterInit, erf, SherpaFloat, \
/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/utils/__init__.py:43: in <module>
    from sherpa.utils import _utils, _psf
E   ImportError: cannot import name '_psf' from partially initialized module 'sherpa.utils' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/utils/__init__.py)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================== 2 error in 1.16 seconds ==============================

**Comment by DougBurke** [comment]
Questions:

1. How did you install CIAO 4.14?
2. Is the CIAO environment set up when you tried the `setup.py` call?
3. What does `ciaover` return?
4. Why are you using `sudo` here?

**Comment by ksk321** [comment]
Dear sir,

Thank you for your reply.

*1. I have installed CIAO-4.14 using ciao-install script.*
*2. yes. I tried setting Ciao environment. but it shows error message which
I mentioned. *




*3. ciaoverCIAO 4.14 Tuesday, November 23, 2021  bindir      :
/home/skk/CIAO-4.14/ciao-4.14/bin  CALDB       : 4.9.8*

*4. When I used without sudo, permission denied. So I used sudo command. *


*The output without using sudo command:*





























***@***.***:~/deproject-main$ python3 setup.py testWARNING:
The wheel package is not available.running pytesterror: can't create or
remove files in install directoryThe following error occurred while trying
to add or remove files in theinstallation directory:    [Errno 13]
Permission denied: './.eggs/test-easy-install-5397.write-test'The
installation directory you specified (via --install-dir, --prefix, orthe
distutils default setting) was:    ./.eggsPerhaps your account does not
have write access to this directory?  If theinstallation directory is a
system-owned directory, you may need to sign inas the administrator or
"root" account.  If you do not have administrativeaccess to this machine,
you may wish to choose a different installationdirectory, preferably one
that is listed in your PYTHONPATH environmentvariable.For information on
other options, you may wish to consult thedocumentation at:
https://setuptools.readthedocs.io/en/latest/easy_install.html
<https://setuptools.readthedocs.io/en/latest/easy_install.html>Please make
the appropriate changes for your system and try again.*

**Comment by DougBurke** [comment]
Unfortunately I can not replicate this. 

From you r original error report I see paths like

```
ImportError while importing test module '/home/skk/deproject-main/tests/test_deproject.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_deproject.py:13: in
from deproject.deproject import Deproject
/usr/local/lib/python3.8/dist-packages/deproject-0.2.1-py3.8.egg/deproject/init.py:12: in
???
/usr/local/lib/python3.8/dist-packages/deproject-0.2.1-py3.8.egg/deproject/deproject.py:25: in
???
/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/plot/init.py:59: in
from sherpa.utils import NoNewAttributesAfterInit, erf, SherpaFloat,
/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/utils/init.py:43: in
from sherpa.utils import _utils, _psf
E ImportError: cannot import name '_psf' from partially initialized module 'sherpa.utils' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/sherpa-4.14.1-py3.8-linux-x86_64.egg/sherpa/utils/init.py)
```

These are not the paths I would expect if you had CIAO installed. If you had used `ciao-install` then it should be talking about some path relative to the CIAO installation - in your case `/home/skk/CIAO-4.14/ciao-4.14/`(it you had installed CIAO 4.14. with `conda` it would be a different path, but again not in `/usr/local/`).

What is the output of `ciaover -v`?

**Comment by ksk321** [comment]
I have installed CIAO using ciao-install.

The output of ciaover -v :

***@***.***:~$ ciaover -v
The current environment is configured for:
  CIAO        : CIAO 4.14 Tuesday, November 23, 2021
  Tools       : Package release 1  Tuesday, November 23, 2021
  Sherpa      : Package release 1  Tuesday, November 23, 2021
  Obsvis      : Package release 1  Tuesday, November 23, 2021
  Core        : Package release 1  Tuesday, November 23, 2021
  Contrib     : Package release 2  Tuesday, April 19, 2022
  bindir      : /home/skk/CIAO-4.14/ciao-4.14/bin
  Python path : /home/skk/CIAO-4.14/ciao-4.14/ots/bin
  CALDB       : 4.9.8

CIAO Installation: Linux
System information:
Linux skk-HP-15-Notebook-PC 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu
Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DougBurke** [comment]
For some reason it's trying to use a different python, not the CIAO one. If you do `which python` do you get back ` `/home/skk/CIAO-4.14/ciao-4.14/bin/python` or something else?

Can you also send the output of `printenv` (you might want to remove any private environment variables that are set first)?

**Comment by DougBurke** [comment]
I have just uploaded version 0.2.2 of deproject to pypi - see https://pypi.org/project/deproject/ - so hopefully you don't need to try installing from github and should just be able to say

```
pip3 install deproject
```

from within a CIAO environment.

**Comment by ksk321** [comment]
Thank you sir. I will try to install it.

**Comment by ksk321** [comment]
Dear Sir,

I successfully installed deproject v 0.2.2 using the link you provided.
I ran "ciao4.14" and after that "pip3 install deproject" in the terminal.
Now, I am able to use deproject.
Thank you very much sir for giving your valuable time to solve my problem.


Sincerely yours,
Sonali

**Comment by DougBurke** [comment]
Sorry it took so long to resolve.

**Comment by ksk321** [comment]
The output is :

***@***.***:~$ which python*


***@***.***:~$ printenv*
SHELL=/bin/bash
SESSION_MANAGER=local/skk-HP-15-Notebook-PC:@
/tmp/.ICE-unix/1699,unix/skk-HP-15-Notebook-PC:/tmp/.ICE-unix/1699
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_MENU_PREFIX=gnome-
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LANGUAGE=en_IN:en
GNOME_SHELL_SESSION_MODE=ubuntu
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
***@***.***=ibus
DESKTOP_SESSION=ubuntu
SSH_AGENT_PID=1656
GTK_MODULES=gail:atk-bridge
PWD=/home/skk
LOGNAME=skk
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_TYPE=x11
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
XAUTHORITY=/run/user/1000/gdm/Xauthority
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
WINDOWPATH=2
HOME=/home/skk
USERNAME=skk
IM_CONFIG_PHASE=1
LANG=en_IN
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=ubuntu:GNOME
VTE_VERSION=6003
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/b28aa8ca_56e6_441b_bc8b_958598602095
INVOCATION_ID=0f59f395d8834d239618429648087113
MANAGERPID=1478
HEADAS=/home/skk/heasoft-6.29/x86_64-pc-linux-gnu-libc2.31
GJS_DEBUG_OUTPUT=stderr
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=skk
GNOME_TERMINAL_SERVICE=:1.92
DISPLAY=:0
SHLVL=1
QT_IM_MODULE=ibus
XDG_RUNTIME_DIR=/run/user/1000
JOURNAL_STREAM=8:41700
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
PATH=/home/skk/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
GDMSESSION=ubuntu
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
OLDPWD=/home/skk/sam1/RXCJ1023.8-2715/9400
_=/usr/bin/printenv
